"""Create email captures table

Revision ID: f89de611f436
Revises: 
Create Date: 2025-08-06 22:16:28.711746

"""
from alembic import op
import sqlalchemy as sa


revision = 'f89de611f436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_captures_code', 'email_captures', ['code'], unique=False)
    op.create_index('idx_email_captures_email', 'email_captures', ['email'], unique=False)
    op.create_index(op.f('ix_email_captures_code'), 'email_captures', ['code'], unique=True)
    op.create_index(op.f('ix_email_captures_email'), 'email_captures', ['email'], unique=True)
    op.create_index(op.f('ix_email_captures_id'), 'email_captures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_captures_id'), table_name='email_captures')
    op.drop_index(op.f('ix_email_captures_email'), table_name='email_captures')
    op.drop_index(op.f('ix_email_captures_code'), table_name='email_captures')
    op.drop_index('idx_email_captures_email', table_name='email_captures')
    op.drop_index('idx_email_captures_code', table_name='email_captures')
    op.drop_table('email_captures')
    # ### end Alembic commands ###